M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date mar. 08 avril 2025 23:13:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-08T23:13:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X31.496Y-81.28
X31.496Y-128.016
X111.76Y-81.28
X111.76Y-128.016
T0
M30
